default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: crypto_rates_dev

test:
  <<: *default
  database: crypto_rates_test

production:
  <<: *default
  database: crypto_rates_prod
